Reduce AVR RAM by 1K, with maybe slight reduction in Flash ROM
lxrobotics/Arduino_CRC32 pull request #13
Opened 2021-08-11 23:04 UTC by brewmanz

My Nanos have 2K of RAM, and this uses over half of it. 
I have added an option (#define CRC32_AVR_FLASH_TABLE) that shifts crc_table into AVR Flash memory, saves 1K of RAM and a few bytes of Flash. 
It seems to test OK, and save memory.

2021-08-11 23:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/arduino-libraries/Arduino_CRC32?pullRequest=13) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/arduino-libraries/Arduino_CRC32?pullRequest=13) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/arduino-libraries/Arduino_CRC32?pullRequest=13) it.</sub>

2021-08-18 06:13 UTC, aentinger requested changes

2021-08-18 06:13 UTC, aentinger commented on src/crc.h
> +#define CRC32_AVR_FLASH_TABLE // reduces my test to 6322/430, else 6328/1454
As I understand it by defining `CRC32_AVR_FLASH_TABLE` here you enable the AVR macros (`PROGMEM`, `pgm_read_dword`) for all platforms. I suggest to replace `CRC32_AVR_FLASH_TABLE` with `ARDUINO_ARCH_AVR` and eliminate this line. This should have the same effect.

2021-08-18 06:40 UTC, brewmanz commented on src/crc.h
> +#define CRC32_AVR_FLASH_TABLE // reduces my test to 6322/430, else 6328/1454
My code is perhaps more of a Proof Of Concept; I'm only familiar with the AVR CPUs, and I struggle to work out what #DEFINE's happen for those. I'm sure that those with more experience across different CPUs can work out a better way to activate storage of the array just in Flash rather than (or 'as well as') RAM for AVRs - and maybe for other CPUs, too.

2021-08-18 12:23 UTC, aentinger commented on src/crc.h
> +#define CRC32_AVR_FLASH_TABLE // reduces my test to 6322/430, else 6328/1454
I've pushed f36acd293a8bdc836920cc301d1366deb7f7672b which fixes this.

2021-08-18 12:35 UTC, merged